#!/bin/bash
sleep 15
/home/com/e
x=0
sleep 5
while [ $x -le 0 ]
do
  	echo "Welcome"
  	/home/com/e
	if ping -c1 google.com; 
	then 
    	echo "Hay conexión"; 
  		x=$(( $x + 1 ))
  	else 
        echo "no tienes conexion"; 
	fi
done
echo "ya esta lista la conexión";
/home/upd/u;
sleep 10;
/home/prog/p;
