#!/bin/bash
sleep 15
/home/com/e
if ping -c1 google.com; 
then 
   	echo "Hay conexión"; 
	x=$(( $x + 1 ))
	/home/upd/u;
	sleep 10;
	/home/prog/p;
else 
    echo "no tienes conexion";
    /home/com/e
    if ping -c1 google.com; 
	then 
   		echo "Hay conexión"; 
		x=$(( $x + 1 ))
		/home/upd/u;
		sleep 10;
		/home/prog/p;
	fi
fi
